version: "3.8"
services:
  apex_db:
    image: postgres:15-alpine
    container_name: apex_db
    environment:
      POSTGRES_DB: apex_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always
